services:
  - type: web
    name: hospital-pharmacy-api
    runtime: node
    rootDir: back_end
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: hospital-pharmacy-web
    runtime: node
    rootDir: front_end
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://hospital-pharmacy-api.onrender.com 